name: Build, Upload to IAS and share on slack.
on:
  push:
    branches:
      - git_action
jobs:

  job1:
    name: Start Message job
    runs-on: ubuntu-latest
    steps:
      - name : message start
        uses: rtCamp/action-slack-notify@v2.1.0
        env:
          # Your slack webhook GitHub secret
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          # Slack channel where you want to notify
          SLACK_CHANNEL: ${{ secrets.SLACK_CHANNEL }}
          SLACK_USERNAME: "Carla Android"
          SLACK_TITLE: "Carla Android"
          SLACK_MESSAGE: "Create Apk And Bundle Started"
          SHOW_ACTIONS_URL: false


  job2:
    name: Building app
    runs-on: ubuntu-latest
    steps:

      - name: Checking out branch
        uses: actions/checkout@v2
        with:
          ref: git_action
      - name: Settting up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Runing build command


        # create aab - bundle
        run: ./gradlew bundleRelease
      - name: Uploading build
        uses: actions/upload-artifact@v2
        with:
          name: bundle
          path: app/build/outputs/bundle/release/app-release.aab



      - name: bundle
        uses: MeilCli/slack-upload-file@v1
        id: messageBundle
        with:
          slack_token: ${{ secrets.SLACK_TOKEN }}
          channels: ${{ secrets.SLACK_CHANNEL }}
          file_path: app/build/outputs/bundle/release/app-release.aab
          file_name: 'app-release.aab'
          file_type: 'aab'
          initial_comment: 'Powered by Carla Android'


  job3:
    name: Building app
    runs-on: ubuntu-latest
    steps:

      - name: Checking out branch
        uses: actions/checkout@v2
        with:
          ref: git_action

      - name: Settting up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

          # create apk
      - name: Runing build command
        run: ./gradlew assembleRelease

      - name: Uploading build
        uses: actions/upload-artifact@v2
        with:
          name: apk
          path: app/build/outputs/apk/release/app-release.apk



      - name: apk
        uses: MeilCli/slack-upload-file@v1
        id: messageApk
        with:
          slack_token: ${{ secrets.SLACK_TOKEN }}
          channels: ${{ secrets.SLACK_CHANNEL }}
          file_path: app/build/outputs/apk/release/app-release.apk
          file_name: 'app-release.apk'
          file_type: 'apk'
          initial_comment: 'Powered by Carla Android'





