name: Build, Upload to IAS and share on slack.
on:
  push:
    branches:
      # Specify branch from where you are sharing build
      -  git_action
jobs:
  upload_to_internal_app_sharing:
    name: Uploading build to IAS
    runs-on: ubuntu-latest
  - name: Sharing on slack
      uses: rtCamp/action-slack-notify@v2.1.0
      env:
              # Your slack webhook GitHub secret
      SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
              # Slack channel where you want to notify
      SLACK_CHANNEL:  ${{secrets.SLACK_CHANNEL}}
      SLACK_USERNAME: "JARVIS"
      SLACK_TITLE: "Internal testing build"
      SLACK_MESSAGE: "test"


