name: Build, Upload to IAS and share on slack.
on:
  push:
    branches:
      # Specify branch from where you are sharing build
      - git_action
jobs:
  build:
    name: Building app
    runs-on: ubuntu-latest
    steps:

      - name: start Create Apk and Bundle
        uses: rtCamp/action-slack-notify@v2.1.0
        env:
          # Your slack webhook GitHub secret
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          # Slack channel where you want to notify
          SLACK_CHANNEL: ${{ secrets.SLACK_CHANNEL }}
          SLACK_USERNAME: "Carla Android"
          SLACK_TITLE: "Carla Android"
          SLACK_MESSAGE: "Create Apk And Bundle Started"
          SHOW_ACTIONS_URL: false



      - name: Checking out branch
        uses: actions/checkout@v2
        with:
          # Specify branch to checkout
          ref: git_action
      - name: Settting up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Runing build command
        # Run your own gradle command to generate build.
        run: ./gradlew bundleRelease
      - name: Uploading build
        uses: actions/upload-artifact@v2
        with:
          name: bundle
          path: app/build/outputs/bundle/release/app-release.aab

  post:
    runs-on: ubuntu-latest
    steps:
      - run: 'echo ${{ github.event.inputs.message }} > message.txt'
      - uses: MeilCli/slack-upload-file@v1
        id: message
        with:
          slack_token: ${{ secrets.SLACK_TOKEN }}
          channels: ${{ secrets.SLACK_CHANNEL }}
          file_path: 'message.txt'
          file_name: 'message.txt'
          file_type: 'abb'
          initial_comment: 'post by slack-upload-file'
      - run: 'echo ${{ fromJson(steps.message.outputs.response).file.permalink }}'