name: Build, Upload to IAS and share on slack.
on:
  push:
    branches:
      - git_action
jobs:

  job1:
    name: What's New
    runs-on: ubuntu-latest
    steps:

      - name: Uploading build
        uses: actions/upload-artifact@v2
        with:
          name: What's New
          path: app/whats_new/what_is_new.txt

      - name : What's New
        uses: MeilCli/slack-upload-file@v1
        id: messageBundle
        with:
            slack_token: ${{ secrets.SLACK_TOKEN }}
            channels: ${{ secrets.SLACK_CHANNEL }}
            file_path: app/whats_new/what_is_new.txt
            file_name: 'what_is_new.txt'
            file_type: 'txt'
            initial_comment: 'Powered by Carla Android'


  job2:
    name: Building app
    runs-on: ubuntu-latest
    steps:

      - name: Checking out branch
        uses: actions/checkout@v2
        with:
          ref: git_action
      - name: Settting up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Runing build command


        # create aab - bundle
        run: ./gradlew bundleRelease
      - name: Uploading build
        uses: actions/upload-artifact@v2
        with:
          name: bundle
          path: app/build/outputs/bundle/release/Carla_5_1_8.aab



      - name: bundle
        uses: MeilCli/slack-upload-file@v1
        id: messageBundle
        with:
          slack_token: ${{ secrets.SLACK_TOKEN }}
          channels: ${{ secrets.SLACK_CHANNEL }}
          file_path: app/build/outputs/bundle/release/app-release.aab
          file_name: 'app-release.aab'
          file_type: 'aab'
          initial_comment: 'Powered by Carla Android'


  job3:
    name: Building app
    runs-on: ubuntu-latest
    steps:

      - name: Checking out branch
        uses: actions/checkout@v2
        with:
          ref: git_action

      - name: Settting up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

          # create apk
      - name: Runing build command
        run: ./gradlew assembleRelease

      - name: Uploading build
        uses: actions/upload-artifact@v2
        with:
          name: apk
          path: app/build/outputs/apk/release/Carla_5_1_8.apk



      - name: apk
        uses: MeilCli/slack-upload-file@v1
        id: messageApk
        with:
          slack_token: ${{ secrets.SLACK_TOKEN }}
          channels: ${{ secrets.SLACK_CHANNEL }}
          file_path: app/build/outputs/apk/release/Carla_5_1_8.apk
          file_name: 'app-release.apk'
          file_type: 'apk'
          initial_comment: 'Powered by Carla Android'





