name: Build, Upload to IAS and share on slack.
on:
  push:
    branches:
      # Specify branch from where you are sharing build
      - git_action
jobs:
  build:
    name: Building app
    runs-on: ubuntu-latest
    steps:





      - name: Checking out branch
        uses: actions/checkout@v2
        with:
          # Specify branch to checkout
          ref: git_action
      - name: Settting up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Runing build command
        # Run your own gradle command to generate build.
        # Run your own gradle command to generate build.
        # Run your own gradle command to generate build.
        # Run your own gradle command to generate build.
        # Run your own gradle command to generate build.



        run: ./gradlew bundleRelease

      - name: Uploading build
        uses: actions/upload-artifact@v2
        with:
          name: bundle
          path: app/build/outputs/bundle/release/app-release.aab


      - name: updoad to slack
        uses: MeilCli/slack-upload-file@v1
        id: message
        with:
          slack_token: ${{ secrets.SLACK_TOKEN }}
          channels: ${{ secrets.SLACK_CHANNEL }}
          file_path: app/build/outputs/bundle/release/app-release.aab
          file_name: 'app-release.aab'
          file_type: 'aab'
          initial_comment: 'post by slack-upload-file'

